// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
    static FirebaseOptions get currentPlatform {
        if (kIsWeb) {
            return web;
        }
        switch (defaultTargetPlatform) {
            case TargetPlatform.android:
                return android;
            case TargetPlatform.iOS:
                return ios;
            case TargetPlatform.macOS:
                throw UnsupportedError(
                    'DefaultFirebaseOptions have not been configured for macos - '
                    'you can reconfigure this by running the FlutterFire CLI again.',
                );
            case TargetPlatform.windows:
                throw UnsupportedError(
                    'DefaultFirebaseOptions have not been configured for windows - '
                    'you can reconfigure this by running the FlutterFire CLI again.',
                );
            case TargetPlatform.linux:
                throw UnsupportedError(
                    'DefaultFirebaseOptions have not been configured for linux - '
                    'you can reconfigure this by running the FlutterFire CLI again.',
                );
            default:
                throw UnsupportedError(
                    'DefaultFirebaseOptions are not supported for this platform.',
                );
        }
    }

    static const FirebaseOptions web = FirebaseOptions(
        apiKey: 'AIzaSyBM6iT0ZJXBcEJvMcCnGu0ugIeLUNQoUcA',
        appId: '1:533788406462:web:00e9b27d8a660752c424ef',
        messagingSenderId: '533788406462',
        projectId: 'socialmediaapp-1aa68',
        authDomain: 'socialmediaapp-1aa68.firebaseapp.com',
        storageBucket: 'socialmediaapp-1aa68.firebasestorage.app',
        measurementId: 'G-NWD31QS9CQ',
    );

    static const FirebaseOptions android = FirebaseOptions(
        apiKey: 'AIzaSyDxlOhnQ6-A_V97A5kqyQcXUrQ32-3569o',
        appId: '1:533788406462:android:6fe69f780e665bfcc424ef',
        messagingSenderId: '533788406462',
        projectId: 'socialmediaapp-1aa68',
        storageBucket: 'socialmediaapp-1aa68.firebasestorage.app',
    );

    static const FirebaseOptions ios = FirebaseOptions(
        apiKey: 'AIzaSyDlIgKUO-V_aob4usEf6v52lHDOLJNP_oQ',
        appId: '1:533788406462:ios:b53b4ebc3ae228b5c424ef',
        messagingSenderId: '533788406462',
        projectId: 'socialmediaapp-1aa68',
        storageBucket: 'socialmediaapp-1aa68.firebasestorage.app',
        iosBundleId: 'com.example.socialMediaApp',
    );
}
